// Auto-generated by design-core/scripts/gen-ts-types.js.
// Source: z-editor/include/ui-event/z-ui-handele-event.h

export enum ZUIEventType {
  MouseDown = 0,
  MouseMove = 1,
  MouseUp = 2,
  Unknown = 3,
}

export interface ZUIEvent {
  type: ZUIEventType;
  x: number;
  y: number;
}
